### PR TITLE
fix(FavoriteWebsites): add newline html entity to TextArea placeholder

### PR DESCRIPTION
**Pull request by fitrahmunir**
## Summary
Fixes issue #152 

## Details
The placeholder from FavoriteWebsites form input not aligned

### Why?
Putting new lines in HTML might not work on all browsers, and sometimes need a bit of CSS and Javascript

### How?
We can add an HTML entity of new line (&#10\;) to separate the sentences

## Checks
- [x] Did you reference the issue? 
- [x] Does this commit follow SRP?

### CODE REVIEW

**Review by AkaraTawng — COMMENTED** [review]
Hi, Fitrah. Can you provide a screenshot of the UI so I can see the effect of your changes? Thanks!

**Comment by fitrahmunir** [comment]
> Hi, Fitrah. Can you provide a screenshot of the UI so I can see the effect of your changes? Thanks!

Yes, here's the screenshot:
Screen Shot 2023-07-31 at 11 01 51 AM

**Comment by AkaraTawng** [comment]
The goal of this issue is to move the placeholder text more into the top left corne as there is currently too much space at the top and on the left of the placeholder text. This will need to be done via CSS.

**Comment by AkaraTawng** [comment]
You might notice that the proportions are now too big. That is because I added the viewport meta tag into the head of the HTML file which has changed the zoom ratio. I'm currently rewriting the default mobile styles to fix the proportions.

**Comment by fitrahmunir** [comment]
> The goal of this issue is to move the placeholder text more into the top left corne as there is currently too much space at the top and on the left of the placeholder text. This will need to be done via CSS.

Yes, this can be achieved by set padding on TextArea. May I help you?

**Comment by AkaraTawng** [comment]
Yes, definitely. Please let me know if you have any questions regarding the
codebase - how it works, where things are, etc. I'm happy to explain it for
you.

**Pull request closed without merging**
